name: Bug Report 🐛
description: Create a report to help identify a bug
title: "[Bug]: "
labels: ["Type - Bug"]
assignees:
  - olesia-kochergina
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    attributes:
      label: Are you running the latest version?
      description: Please check the latest release version and the version of software you are running.
      options:
      - label: I am running the latest software
        required: true
  - type: checkboxes
    attributes:
      label: Did you check the debugging guide and FAQs?
      description: Please check the documentation to ensure the bug is not covered there.
      options:
      - label: I have checked the documentation
        required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: The issue...
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      multiple: true
      options:
        - Other
        - Nvidia Jetson Nano
        - Nvidia Jetson Xavier NX
        - ASUS Tinkerboard
        - Raspberry Pi
        - x86_64 Intel
        - x86_64 Nvidia
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What OS are you using?
      multiple: true
      options:
        - Other
        - Linux
        - Windows
        - MacOS
        - Android
        - iOS
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Identify the version number
      placeholder: ex. v1.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
